version: '3'

services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - flutter-pub-cache:/root/.pub-cache
    ports:
      - "8080:8080"
      - "8085:8085"  # Adicionando porta para servidor web de download do APK
    tty: true

volumes:
  flutter-pub-cache: