name: barcode_scanner
description: Leitor de código de barras.
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  yaml: ^3.1.2
  package_info_plus: ^4.2.0
  audioplayers: ^5.2.1
  
  # Dependências para verificação e instalação de atualizações
  http: ^1.1.0
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  permission_handler: ^10.4.5
  dio: ^5.3.2
  install_plugin: ^2.1.0
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/sounds/beep.mp3
    
# Configuração do ícone do aplicativo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
